{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.1.71.201', port=49152): Max retries exceeded with url: /metrics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3ba91fae30>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_exporter_endpoint","uid":"7c6830458ffe8222","parentUid":"93603d06f6ee84713a5be395eb7fa14b","status":"broken","time":{"start":1720143444094,"stop":1720143787181,"duration":343087},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["asyncio","abort_on_fail","@pytest.mark.skipif(False, reason='Requires amd64 architecture')","group(1)"]}],"uid":"93603d06f6ee84713a5be395eb7fa14b"},{"name":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmysql-router-k8s/0 [idle] active: Router 8.0.37+testupgrade running (restart pending); Charmed operator 1.2+ee5d2ff\n  mysql-router-k8s/1 [idle] active: Router 8.0.37+testupgrade running (restart pending); Charmed operator 1.2+ee5d2ff\n  mysql-router-k8s/2 [idle] active: Router 8.0.37+testupgrade running; Charmed operator 1.2+ee5d2ff","children":[{"name":"test_fail_and_rollback","uid":"6eb52b067bad95b7","parentUid":"1a52885260defcf448366ce00d0cb3ef","status":"broken","time":{"start":1720143746359,"stop":1720145020148,"duration":1273789},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["asyncio","abort_on_fail","group(1)"]}],"uid":"1a52885260defcf448366ce00d0cb3ef"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}